title: 株式会社ZUMEN
logo: https://github.com/pages-themes/minimal/raw/master/assets/img/logo.png
description: zumen-co-jp
show_downloads: false
google_analytics:
encoding: utf-8
highlighter: rouge
plugins: [jekyll-lunr-js-search]
image: /assets/img/sample.jpg
